/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ImgCastDiscordPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  webhookUrl: "",
  username: "ImgCast Bot"
};
var ImgCastDiscordPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new ImgCastDiscordSettingTab(this.app, this));
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor, view) => {
        this.addImageUploadMenuItem(menu, editor, view);
      })
    );
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian.TFile && this.isImageFile(file)) {
          menu.addItem((item) => {
            item.setTitle("Upload to Discord").setIcon("upload").onClick(() => this.uploadImageToDiscord(file));
          });
        }
      })
    );
    this.addImageViewerContextMenu();
  }
  onunload() {
  }
  addImageViewerContextMenu() {
    this.registerInterval(
      window.setInterval(() => {
        const images = document.querySelectorAll("img[src]:not([data-imgcast-context])");
        images.forEach((img) => {
          console.log("Found image:", img.src);
          const viewer = img.closest(".image-viewer, .modal, .popup");
          if (viewer) {
            console.log("Image is in viewer:", viewer.className);
          }
          img.setAttribute("data-imgcast-context", "true");
          img.addEventListener("contextmenu", (e) => {
            e.preventDefault();
            e.stopPropagation();
            const menu = this.createImageContextMenu(img);
            document.body.appendChild(menu);
            menu.style.left = e.pageX + "px";
            menu.style.top = e.pageY + "px";
            const removeMenu = () => {
              menu.remove();
              document.removeEventListener("click", removeMenu);
            };
            setTimeout(() => {
              document.addEventListener("click", removeMenu);
            }, 100);
          });
        });
      }, 1e3)
    );
  }
  createImageContextMenu(img) {
    const menu = document.createElement("div");
    menu.className = "imgcast-context-menu";
    menu.style.cssText = `
			position: fixed;
			background: var(--background-primary);
			border: 1px solid var(--background-modifier-border);
			border-radius: 6px;
			padding: 4px 0;
			box-shadow: var(--shadow-s);
			z-index: 10000;
			min-width: 150px;
		`;
    const menuItem = document.createElement("div");
    menuItem.style.cssText = `
			padding: 8px 12px;
			cursor: pointer;
			display: flex;
			align-items: center;
			gap: 8px;
			color: var(--text-normal);
			font-size: var(--font-ui-small);
		`;
    menuItem.innerHTML = `
			<span style="width: 16px; height: 16px; display: inline-block;">\u2B06\uFE0F</span>
			Upload to Discord
		`;
    menuItem.addEventListener("mouseenter", () => {
      menuItem.style.background = "var(--background-modifier-hover)";
    });
    menuItem.addEventListener("mouseleave", () => {
      menuItem.style.background = "";
    });
    menuItem.addEventListener("click", async () => {
      menu.remove();
      await this.handleImageUploadFromSrc(img.src);
    });
    menu.appendChild(menuItem);
    return menu;
  }
  async handleImageUploadFromSrc(src) {
    try {
      console.log("Handling image upload from src:", src);
      let file = this.app.workspace.getActiveFile();
      console.log("Active file:", file == null ? void 0 : file.path, "Is image:", file ? this.isImageFile(file) : false);
      if (!file || !this.isImageFile(file)) {
        if (src.startsWith("app://")) {
          let path = src.replace("app://", "");
          if (path.startsWith("/")) {
            path = path.slice(1);
          }
          console.log("Looking for file with path:", path);
          const abstractFile = this.app.vault.getAbstractFileByPath(path);
          if (abstractFile instanceof import_obsidian.TFile) {
            file = abstractFile;
          }
        } else {
          const allFiles = this.app.vault.getFiles();
          const srcFileName = src.split("/").pop() || src;
          for (const vaultFile of allFiles) {
            if (this.isImageFile(vaultFile) && vaultFile.name === srcFileName) {
              console.log("Found file by name:", vaultFile.path);
              file = vaultFile;
              break;
            }
          }
        }
      }
      console.log("Final file found:", file == null ? void 0 : file.path, "Is image:", file ? this.isImageFile(file) : false);
      if (file && this.isImageFile(file)) {
        await this.uploadImageToDiscord(file);
      } else {
        new import_obsidian.Notice(`Could not find image file from context. Src: ${src}`);
      }
    } catch (error) {
      console.error("Error handling image upload:", error);
      new import_obsidian.Notice(`\u274C Upload failed: ${error.message}`);
    }
  }
  async uploadBlobToDiscord(blob, filename) {
    if (!this.settings.webhookUrl) {
      new import_obsidian.Notice("Please configure Discord webhook URL in settings");
      return;
    }
    try {
      const formData = new FormData();
      formData.append("file1", blob, filename);
      formData.append("username", this.settings.username);
      formData.append("content", "Image upload");
      const response = await fetch(this.settings.webhookUrl, {
        method: "POST",
        body: formData
      });
      if (response.ok) {
        new import_obsidian.Notice(`\u2705 ${filename} uploaded to Discord successfully!`);
      } else {
        const errorText = await response.text();
        new import_obsidian.Notice(`\u274C Failed to upload: ${response.status} ${errorText}`);
      }
    } catch (error) {
      console.error("Error uploading to Discord:", error);
      new import_obsidian.Notice(`\u274C Upload failed: ${error.message}`);
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  isImageFile(file) {
    const imageExtensions = ["png", "jpg", "jpeg", "gif", "webp", "bmp", "svg"];
    const extension = file.extension.toLowerCase();
    return imageExtensions.includes(extension);
  }
  addImageUploadMenuItem(menu, editor, view) {
    const selectedText = editor.getSelection();
    const cursorPos = editor.getCursor();
    const line = editor.getLine(cursorPos.line);
    const imageRegex = /!\[.*?\]\((.*?)\)/;
    const match = imageRegex.exec(selectedText || line);
    if (match) {
      const imagePath = match[1];
      menu.addItem((item) => {
        item.setTitle("Upload image to Discord").setIcon("upload").onClick(async () => {
          const file = this.app.vault.getAbstractFileByPath(imagePath);
          if (file instanceof import_obsidian.TFile && this.isImageFile(file)) {
            await this.uploadImageToDiscord(file);
          } else {
            new import_obsidian.Notice("Could not find image file");
          }
        });
      });
    }
  }
  async uploadImageToDiscord(file) {
    if (!this.settings.webhookUrl) {
      new import_obsidian.Notice("Please configure Discord webhook URL in settings");
      return;
    }
    try {
      const buffer = await this.app.vault.readBinary(file);
      const blob = new Blob([buffer], { type: this.getMimeType(file.extension) });
      const formData = new FormData();
      formData.append("file1", blob, file.name);
      formData.append("username", this.settings.username);
      formData.append("content", "Image upload");
      const response = await fetch(this.settings.webhookUrl, {
        method: "POST",
        body: formData
      });
      if (response.ok) {
        new import_obsidian.Notice(`\u2705 ${file.name} uploaded to Discord successfully!`);
      } else {
        const errorText = await response.text();
        new import_obsidian.Notice(`\u274C Failed to upload: ${response.status} ${errorText}`);
      }
    } catch (error) {
      console.error("Error uploading to Discord:", error);
      new import_obsidian.Notice(`\u274C Upload failed: ${error.message}`);
    }
  }
  getMimeType(extension) {
    const ext = extension.toLowerCase();
    const mimeTypes = {
      "png": "image/png",
      "jpg": "image/jpeg",
      "jpeg": "image/jpeg",
      "gif": "image/gif",
      "webp": "image/webp",
      "bmp": "image/bmp",
      "svg": "image/svg+xml"
    };
    return mimeTypes[ext] || "application/octet-stream";
  }
};
var ImgCastDiscordSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "ImgCast Discord Settings" });
    new import_obsidian.Setting(containerEl).setName("Discord Webhook URL").setDesc("The webhook URL for your Discord channel").addText((text) => text.setPlaceholder("https://discord.com/api/webhooks/...").setValue(this.plugin.settings.webhookUrl).onChange(async (value) => {
      this.plugin.settings.webhookUrl = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Username").setDesc("The username that will appear when uploading images").addText((text) => text.setPlaceholder("ImgCast Bot").setValue(this.plugin.settings.username).onChange(async (value) => {
      this.plugin.settings.username = value;
      await this.plugin.saveSettings();
    }));
  }
};
